config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :albums
  resources :photos
  

end

app/models/album.rb
class Album < ActiveRecord::Base
	
	belongs_to :user
	has_many :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
  	@albums = Album.all
  end

  def new
  	@album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.save
    redirect_to albums_path
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])    
  end

  def update
    @album = Album.find(params[:id])
      if @album.update(album_params)
        redirect_to album_path(@album.id)
      else
        render 'edit'
      end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
  end

  private

  def album_params
  	params.require(:album).permit(:id, :name, :category)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/edit.html.erb
<h2>Edit Album</h2>


<%= form_for (@album) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  
  <%= f.submit "Edit Album" %>
  </div>
<% end %>
<br> <%= link_to "Back", album_path%>

app/views/albums/index.html.erb
<div class="admin_login"><%= link_to "Admin Login", new_album_path %></div>
<div class="home"><%= link_to "Home", root_path %></div>

<h1>Albums Gallery</h1>

<% @albums.each do |album| %>
  <div>
  	<%= link_to album.name, album_path(album.id) %>    
  </div>
<% end %>

app/views/albums/new.html.erb
<h2>New Albums</h2>
<%= link_to "Back", albums_path %>

<%= link_to "Delete", albums_path%>

<%= form_for (@album) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit "Add Album" %>
<% end %>

app/views/albums/show.html.erb
<h3><%= link_to @album.name %></h3>
<div class="album">
<%= link_to "Edit", edit_album_path(@album.id) %>
<%= link_to "Delete", @album, method: :delete, data:{confirm: "Are you sure you want to delete this album? All photos in it will be permanently deleted!"} %>
</div>
<br><%= link_to "Back", albums_path %>

app/views/home/index.html.erb
<h1>Seven Dreams Photography</h1>
<h3> by Nick Fisher </h3>
<%= link_to "Albums Gallery", albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sevendreams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/edit.html.erb
<h1>Edit Photos</h1>

app/views/photos/index.html.erb
<h1>Index of photos here</h1>

app/views/photos/new.html.erb
<h1> New Photos </h1>

app/views/photos/show.html.erb
<h1>Photo</h1>